apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    name: nginx
    author: richa
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: nginx
