apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    name: nginx
    author: richa
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    name: nginx
