apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  awsElasticBlockStore:
    volumeID: vol-00fc356f5ba4acc8b
    fsType: ext4
