apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    author: richa
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      name: nginx
      labels:
        name: nginx
        author: richa
    spec:
      containers:
        - name: nginx
          image: nginx
