apiVersion: v1
kind: Service
metadata:
  name: custom-website-service
  labels:
    app: custom-website
    author: richa
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
  selector:
    app: custom-website
